language: python
python:
    - "2.7"
before_install:
    - pip install pytest pytest-cov
    - pip install -r Twitter_Utils/requirements.txt
    - pip install coveralls
script:
    - py.test
after_success:
    - coveralls

